name: flutter_notificaciones
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies: 
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  go_router: ^6.2.0
  equatable: ^2.0.5
  firebase_core: ^2.7.1
  firebase_messaging: ^14.7.2
  flutter_lints: ^2.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true

